name: Render Dashboard

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  render-dashboard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gdal-bin \
            libcurl4-openssl-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libgdal-dev \
            libnode-dev \
            libpng-dev \
            libudunits2-dev \
            libx11-dev \
            pandoc

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: dashboard.qmd
          format: dashboard

      - name: Commit rendered file
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add dashboard.html
          git commit -m "Render dashboard.qmd to dashboard.html [skip ci]" || echo "No changes to commit"
          git push
